var request = require('request');http://dish.allrecipes.com/common-ingredient-substitutions/
var cheerio = require('cheerio');
var alt = [];


request('http://dish.allrecipes.com/common-ingredient-substitutions/', function (error, response, html) {
  if (!error && response.statusCode == 200) {
    var $ = cheerio.load(html);
    var i=0;
    $('table tbody tr').each(function(i, element){
      if(i!=0){
      	var a = $(this);
      	// var td=a.children('td').eq(1);
		alt.push(new Object({
			name: a.children('td').eq(0).text(),
			qty: a.children('td').eq(1).text(),
			diff: a.children('td').eq(2).text()
		}))
      }
    });
  }
});

var default_alt = [ { name: 'Allspice',
    qty: '1 teaspoon',
    diff: '1/2 teaspoon cinnamon, 1/4 teaspoon ginger, and 1/4 teaspoon cloves' },
  { name: 'Arrowroot starch',
    qty: '1 teaspoon',
    diff: '1 tablespoon flour OR 1 teaspoon cornstarch' },
  { name: 'Baking mix',
    qty: '1 cup',
    diff: '1 cup pancake mix OR 1 cup Easy Biscuit Mixture' },
  { name: 'Baking powder',
    qty: '1 teaspoon',
    diff: '1/4 teaspoon baking soda plus 1/2 teaspoon cream of tartar OR 1/4 teaspoon baking soda plus 1/2 cup buttermilk (decrease liquid in recipe by 1/2 cup)' },
  { name: 'Baking soda',
    qty: '1 teaspoon',
    diff: '4 teaspoons baking powder OR 1 teaspoon potassium bicarbonate and 1/3 teaspoon salt. NOTE: If the recipe calls for an acidic liquid such as sour cream, yogurt, buttermilk, vinegar, molasses, or citrus juice, you should replace it with the same amount of whole milk' },
  { name: 'Beer',
    qty: '1 cup',
    diff: '1 cup nonalcoholic beer OR 1 cup broth' },
  { name: 'Brandy',
    qty: '1/4 cup',
    diff: '1 teaspoon imitation brandy extract plus enough water to make 1/4 cup' },
  { name: 'Bread crumbs',
    qty: '1 cup',
    diff: '1 cup cracker crumbs OR 1 cup matzo meal OR 1 cup ground oats' },
  { name: 'Broth: beef or chicken',
    qty: '1 cup',
    diff: '1 bouillon cube plus 1 cup boiling water OR 1 tablespoon soy sauce plus enough water to make 1 cup OR 1 cup vegetable broth' },
  { name: 'Brown sugar',
    qty: '1 cup, packed',
    diff: '1 cup white sugar plus 1/4 cup molasses and decrease the liquid in recipe by 1/4 cup OR 1 cup white sugar OR 1 1/4 cups confectioners\' sugar' },
  { name: 'Butter (salted)',
    qty: '1 cup',
    diff: '1 cup margarine OR 1 cup shortening plus 1/2 teaspoon salt OR 7/8 cup vegetable oil plus 1/2 teaspoon salt OR 7/8 cup lard plus 1/2 teaspoon salt' },
  { name: 'Butter (unsalted)',
    qty: '1 cup',
    diff: '1 cup shortening OR 7/8 cup vegetable oil OR 7/8 cup lard' },
  { name: 'Buttermilk',
    qty: '1 cup',
    diff: '1 cup yogurt OR 1 tablespoon lemon juice or vinegar plus enough milk to make 1 cup' },
  { name: 'cheese',
    qty: '1 cup shredded',
    diff: '1 cup shredded Colby cheddar OR 1 cup shredded Monterey Jack cheese' },
  { name: 'Chervil',
    qty: '1 tablespoon chopped fresh',
    diff: '1 tablespoon chopped fresh parsley' },
  { name: 'Chicken base',
    qty: '1 tablespoon',
    diff: '1 cup canned or homemade chicken broth or stock. Reduce liquid in recipe by 1 cup' },
  { name: 'Chocolate(semisweet)',
    qty: '1 ounce',
    diff: '1 (1-ounce) square of unsweetened chocolate plus 4 teaspoons sugar OR 1 ounce semisweet chocolate chips plus 1 teaspoon shortening' },
  { name: 'Chocolate (unsweetened)',
    qty: '1 ounce',
    diff: '3 tablespoons unsweetened cocoa plus 1 tablespoon shortening or vegetable oil' },
  { name: 'Cocoa',
    qty: '1/4 cup',
    diff: '1 (1-ounce) square unsweetened chocolate' },
  { name: 'Condensed cream of mushroom soup',
    qty: '1 (10.75-ounce) can',
    diff: '1 (10.75-ounce) can condensed cream of celery, cream of chicken, or golden mushroom soup' },
  { name: 'Corn syrup',
    qty: '1 cup',
    diff: '1 1/4 cup white sugar plus 1/3 cup water OR 1 cup honey OR 1 cup light treacle syrup' },
  { name: 'Cottage cheese',
    qty: '1 cup',
    diff: '1 cup farmer\'s cheese OR 1 cup ricotta cheese' },
  { name: 'Cracker crumbs',
    qty: '1 cup',
    diff: '\r\n\t\t\t1 cup bread crumbs OR 1 cup matzo mealOR 1 cup ground oats\r\n\t\t\t' },
  { name: 'Cream (half and half)',
    qty: '1 cup',
    diff: '7/8 cup milk plus 1 tablespoon butter' },
  { name: 'Cream (heavy)',
    qty: '1 cup',
    diff: '1 cup evaporated milk OR 3/4 cup milk plus 1/3 cup butter' },
  { name: 'Cream (light)',
    qty: '1 cup',
    diff: '1 cup evaporated milk OR 3/4 cup milk plus 3 tablespoons butter' },
  { name: 'Cream (whipped)',
    qty: '1 cup',
    diff: '1 cup frozen whipped topping, thawed' },
  { name: 'Cream cheese',
    qty: '1 cup',
    diff: '1 cup pureed cottage cheese OR 1 cup plain yogurt, strained overnight in a cheesecloth' },
  { name: 'Cream of tartar',
    qty: '1 teaspoon',
    diff: '2 teaspoons lemon juice or vinegar' },
  { name: 'Crème fraiche',
    qty: '1 cup',
    diff: 'Combine 1 cup of heavy cream and 1 tablespoon of plain yogurt. Let stand for 6 hours at room temperature' },
  { name: 'Egg',
    qty: '1 whole (3 tablespoons or 1.7 oz)',
    diff: '2 1/2 tablespoons of powdered egg substitute plus 2 1/2 tablespoons water OR 1/4 cup liquid egg substitute OR 1/4 cup silken tofu pureed OR 3 tablespoons mayonnaise OR half a banana mashed with 1/2 teaspoon baking powder OR 1 tablespoon powdered flax seed soaked in 3 tablespoons water' },
  { name: 'Evaporated milk',
    qty: '1 cup',
    diff: '1 cup light cream' },
  { name: 'Farmer\'s cheese',
    qty: '8 ounces',
    diff: '8 ounces dry cottage cheese OR 8 ounces creamed cottage cheese, drained' },
  { name: 'Fats for baking',
    qty: '1 cup',
    diff: '1 cup applesauce OR 1 cup fruit puree' },
  { name: 'Flour--Bread',
    qty: '1 cup',
    diff: '1 cup all-purpose flour plus 1 teaspoon wheat gluten (available at health food stores & some supermarkets)' },
  { name: 'Flour--Cake',
    qty: '1 cup',
    diff: '1 cup all-purpose flour minus 2 tablespoons' },
  { name: 'Flour--Self-Rising',
    qty: '1 cup',
    diff: '7/8 cup all-purpose flour plus 1 1/2 teaspoons baking powder and 1/2 teaspoon of salt' },
  { name: 'Garlic',
    qty: '1 clove',
    diff: '1/8 teaspoon garlic powder OR 1/2 teaspoon granulated garlic OR 1/2 teaspoon garlic salt--reduce salt in recipe' },
  { name: 'Gelatin',
    qty: '1 tablespoon, granulated',
    diff: '2 teaspoons agar agar' },
  { name: 'Ginger--dry',
    qty: '1 teaspoon',
    diff: '2 teaspoons chopped fresh ginger' },
  { name: 'Ginger--fresh',
    qty: '1 teaspoon, minced',
    diff: '1/2 teaspoon ground dried ginger' },
  { name: 'Green onion',
    qty: '1/2 cup , chopped',
    diff: '1/2 cup chopped onion OR 1/2 cup chopped leek OR 1/2 cup chopped shallots' },
  { name: 'Hazelnuts',
    qty: '1 cup whole',
    diff: '1 cup macadamia nuts OR 1 cup almonds' },
  { name: 'Herbs--fresh',
    qty: '1 tablespoon chopped fresh',
    diff: '1 teaspoon (chopped or whole leaf) dried herbs' },
  { name: 'Herring',
    qty: '8 ounces',
    diff: '8 ounces of sardines' },
  { name: 'Honey',
    qty: '1 cup',
    diff: '1 1/4 cup white sugar plus 1/3 cup water OR 1 cup corn syrup OR 1 cup light treacle syrup' },
	{ name: 'pepper',
      qty: '1 teaspoon',
      diff: '1 teaspoon Flakes' },
    { name: 'Hot pepper sauce',
    qty: '1 teaspoon',
    diff: '3/4 teaspoon cayenne pepper plus 1 teaspoon vinegar' },
  { name: 'Ketchup',
    qty: '1 cup',
    diff: '1 cup tomato sauce plus 1 teaspoon vinegar plus 1 tablespoon sugar' },
  { name: 'Lard',
    qty: '1 cup',
    diff: '1 cup shortening OR 7/8 cup vegetable oil OR 1 cup butter' },
  { name: 'Lemon grass',
    qty: '2 fresh stalks',
    diff: '1 tablespoon lemon zest' },
  { name: 'Lemon juice',
    qty: '1 teaspoon',
    diff: '1/2 teaspoon vinegar OR 1 teaspoon white wine OR 1 teaspoon lime juice' },
  { name: 'Lemon zest',
    qty: '1 teaspoon',
    diff: '1/2 teaspoon lemon extract OR 2 tablespoons lemon juice' },
  { name: 'Lime juice',
    qty: '1 teaspoon',
    diff: '1 teaspoon vinegar OR 1 teaspoon white wine OR 1 teaspoon lemon juice' },
  { name: 'Lime zest',
    qty: '1 teaspoon',
    diff: '1 teaspoon lemon zest' },
  { name: 'Macadamia nuts',
    qty: '1 cup',
    diff: '1 cup almonds OR 1 cup hazelnuts' },
  { name: 'Mace', qty: '1 teaspoon', diff: '1 teaspoon nutmeg' },
  { name: 'Margarine',
    qty: '1 cup',
    diff: '1 cup shortening plus 1/2 teaspoon salt OR 1 cup butter OR 7/8 cup vegetable oil plus 1/2 teaspoon salt OR 7/8 cup lard plus 1/2 teaspoon salt' },
  { name: 'Mayonnaise',
    qty: '1 cup',
    diff: '1 cup sour cream OR 1 cup plain yogurt' },
  { name: 'Milk--whole',
    qty: '1 cup',
    diff: '1 cup soy milk OR 1 cup rice milk OR 1 cup water or juice OR 1/4 cup dry milk powder plus 1 cup water OR 2/3 cup evaporated milk plus 1/3 cup water' },
  { name: 'Mint--fresh',
    qty: '1/4 cup chopped',
    diff: '1 tablespoon dried mint leaves' },
  { name: 'Molasses',
    qty: '1 cup',
    diff: 'Mix 3/4 cup brown sugar and 1 teaspoon cream of tartar' },
  { name: 'Mustard--prepared',
    qty: '1 tablespoon',
    diff: 'Mix together 1 tablespoon dried mustard, 1 teaspoon water, 1 teaspoon vinegar and 1 teaspoon sugar' },
  { name: 'Onion',
    qty: '1 cup, chopped',
    diff: '1 cup chopped green onions OR 1 cup chopped shallots OR 1 cup chopped leeks OR 1/4 cup dried minced onion OR 1/4 cup onion powder' },
  { name: 'Orange juice',
    qty: '1 tablespoon',
    diff: '1 tablespoon other citrus juice' },
  { name: 'Orange zest',
    qty: '1 tablespoon',
    diff: '1/2 teaspoon orange extract OR 1 teaspoon lemon juice' },
  { name: 'Parmesan cheese',
    qty: '1/2 cup, grated',
    diff: '1/2 cup grated Asiago cheese OR 1/2 cup grated Romano cheese' },
  { name: 'Parsley',
    qty: '1 tablespoon chopped fresh',
    diff: '1 tablespoon chopped fresh chervil OR 1 teaspoon dried parsley' },
  { name: 'Pepperoni', qty: '1 ounce', diff: '1 ounce salami' },
  { name: 'Raisin',
    qty: '1 cup',
    diff: '1 cup dried currants OR 1 cup dried cranberries OR 1 cup chopped pitted prunes' },
  { name: 'Rice--white',
    qty: '1 cup, cooked',
    diff: '1 cup cooked barley OR 1 cup cooked bulgur OR 1 cup cooked brown or wild rice' },
  { name: 'Ricotta',
    qty: '1 cup',
    diff: '1 cup dry cottage cheese OR 1 cup silken tofu' },
  { name: 'Rum',
    qty: '1 tablespoon',
    diff: '1/2 teaspoon rum extract, plus enough water to make 1 tablespoon' },
  { name: 'Saffron',
    qty: '1/4 teaspoon',
    diff: '1/4 teaspoon turmeric' },
  { name: 'Salami', qty: '1 ounce', diff: '1 ounce pepperoni' },
  { name: 'Semisweet chocolate chips',
    qty: '1 cup',
    diff: '1 cup chocolate candies OR 1 cup peanut butter or other flavored chips OR 1 cup chopped nuts OR 1 cup chopped dried fruit' },
  { name: 'Shallots, chopped',
    qty: '1/2 cup',
    diff: '1/2 cup chopped onion, OR 1/2 cup chopped leek OR 1/2 cup chopped green onion' },
  { name: 'Shortening',
    qty: '1 cup',
    diff: '1 cup butter OR 1 cup margarine minus 1/2 teaspoon salt from recipe' },
  { name: 'Sour cream',
    qty: '1 cup',
    diff: '1 cup plain yogurt OR 1 tablespoon lemon juice or vinegar plus enough cream to make 1 cup OR 3/4 cup buttermilk mixed with 1/3 cup butter' },
  { name: 'Sour milk',
    qty: '1 cup',
    diff: '1 tablespoon vinegar or lemon juice mixed with enough milk to make 1 cup: Let stand 5 minutes to thicken' },
  { name: 'Soy sauce',
    qty: '1/2 cup',
    diff: '1/4 cup Worcestershire sauce mixed with 1 tablespoon water' },
  { name: 'Stock--beef or chicken',
    qty: '1 cup',
    diff: '1 cube beef or chicken bouillon dissolved in 1 cup water' },
  { name: 'Sweetened condensed milk',
    qty: '1 (14-ounce) can',
    diff: '3/4 cup white sugar mixed with 1/2 cup water and 1 1/8 cups dry powdered milk: Bring to a boil and cook, stirring frequently, until thickened, about 20 minutes' },
  { name: 'Vegetable oil--for baking',
    qty: '1 cup',
    diff: '1 cup applesauce OR 1 cup fruit puree' },
  { name: 'Vegetable oil--for frying',
    qty: '1 cup',
    diff: '1 cup lard OR 1 cup vegetable shortening' },
  { name: 'Vinegar',
    qty: '1 teaspoon',
    diff: '1 teaspoon lemon or lime juice OR 2 teaspoons white wine' },
  { name: 'White sugar',
    qty: '1 cup',
    diff: '1 cup brown sugar OR 1 1/4 cups confectioners\' sugar OR 3/4 cup honey OR 3/4 cup corn syrup' },
  { name: 'Wine',
    qty: '1 cup',
    diff: '1 cup chicken or beef broth OR 1 cup fruit juice mixed with 2 teaspoons vinegar OR 1 cup water' },
  { name: 'Yeast-active dry',
    qty: '1 (.25-ounce) package',
    diff: '1 cake compressed yeast OR 2 1/2 teaspoons active dry yeast OR 2 1/2 teaspoonsrapid rise yeast' },
  { name: 'Yogurt',
    qty: '1 cup',
    diff: '1 cup sour cream OR 1 cup buttermilk OR 1 cup sour milk' } ]

	module.exports = {
		default_alt
	}
